#!/bin/bash 
#
# Usage: swiftopt.sh [-s sitename] [-p paramfile] [-g gridlist] 

# crash: Report a problem and exit
crash()
{
    echo "$@" >&2
    exit 1
}

# Process command line arguments
while [ $# -gt 0 ]; do
  case $1 in
    -g) gridlist=$2; shift 2;;
    -p) paramfile=$2; shift 2;;
    -s) site=$2; shift 2;;
    *) crash "Usage: $0 [-s sitename] [-p paramfile] [-g gridlist]";;
  esac
done

if [ ! -f "conf/$site.xml" ]; then
   crash "Unable to find configuration file conf/$site.xml"
fi

# Create next unique run id and run directory
rundir=$( echo run??? | sed -e 's/^.*run//' | awk '{ printf("run%03d\n", $1+1)}' )
mkdir $rundir || crash "Unable to create run directory"

# Set parameters
if [ ! -f $paramfile ]; then
   crash "Could not find parameter file $paramfile in params!"
fi

sed -e '/^[[:space:]]*\(#.*\)*$/d' -e 's/#.*//' -e 's/  */=/' -e 's/^/export /' $paramfile > $rundir/params.psims
source $rundir/params.psims

# Extract input_tars
if [ -n "$tar_inputs" ]; then
   echo "Setting up data..."
   tar_files=$( echo $tar_inputs | sed s/,/' '/g )
   for file in $tar_files; do
      extension="${file##*.}"
      if [ "$extension" == "tar" ]; then
         echo "Extracting $file"
         tar xf $file 
      else
         echo "Extracting $file"
         tar xfz $file 
      fi
   done
fi

# Copy required files to the rundir
cp $campaign/*.nc4 $rundir/
cp $gridlist $rundir/gridList.txt
cp RunpSIMS.swift $rundir
cp bin/RunpSIMS.sh $rundir
cp conf/swift.properties $rundir
cp conf/$site.xml $rundir/sites.xml
cp conf/$site.cf $rundir/cf
cp $paramfile $rundir/paramfile
chmod a+rw $rundir/*

# Echo parameters
echo Run directory $rundir: site=$site paramfile=$paramfile gridlist=$gridlist
echo -e "\nParameters:"
cat $rundir/params.psims
echo

# Record arguments in ABOUT file
cat << EOF > $rundir/ABOUT
Running with parameter file $paramfile
Running on site $site
Running with gridlist $gridlist
EOF

# Do the run
cd $rundir
for param in $( awk '{print $1}' paramfile )
do
   arguments="$arguments -$param=${!param}"
done

export SWIFT_HEAP_MAX=5120M
export SWIFT_USERHOME=$PWD

echo "swift -sites.file sites.xml -tc.file tc.data -config cf -resume *.rlog RunpSIMS.swift $arguments 2>&1 | tee -a swift.out" > restart.sh
chmod +x restart.sh

gensites -p cf ../conf/$site.xml > sites.xml
swift -sites.file sites.xml -tc.file tc.data -config cf RunpSIMS.swift $arguments 2>&1 | tee swift.out

echo Generating plot...
../bin/activityplot.pl RunpSIMS-2*.log &> /dev/null
echo Done
