#!/bin/bash
#
# Usage: swiftopt.sh [-s sitename] [-p paramfile] [-g gridlist] 

# crash: Report a problem and exit
crash()
{
    echo "$@" >&2
    exit 1
}

# Find absolute path
abspath()
{
   readlink -f $1
}

# Process command line arguments
while [ $# -gt 0 ]; do
  case $1 in
    -g) gridlist=$2; shift 2;;
    -p) paramfile=$2; shift 2;;
    -s) site=$2; shift 2;;
    *) crash "Usage: $0 [-s sitename] [-p paramfile] [-g gridlist]";;
  esac
done

if [ ! -f "conf/$site.xml" ]; then
   crash "Unable to find configuration file conf/$site.xml"
fi

# Create next unique run id and run directory
export rundir=$( abspath $( echo run??? | sed -e 's/^.*run//' | awk '{ printf("run%03d\n", $1+1)}' ))
mkdir $rundir || crash "Unable to create run directory"

# Set parameters
if [ ! -f $paramfile ]; then
   crash "Could not find parameter file $paramfile in params!"
fi

sed -e '/^[[:space:]]*\(#.*\)*$/d' -e 's/#.*//' -e 's/  */=/' -e 's/^/export /' $paramfile > $rundir/params.psims
source $rundir/params.psims

# Check for work_directory location
if [ -z "$work_directory" ]; then
   work_directory=$rundir
else 
   work_directory=$( abspath $work_directory )/$( basename $rundir )
   if [ -d "$work_directory" ]; then
      crash "Work directory $work_directory already exists"
   fi
   mkdir -p $work_directory
   cp $rundir/params.psims $work_directory
fi

# Copy required files to the work_directory
cp $campaign/*.nc4 $work_directory/
cp $gridlist $work_directory/gridList.txt
cp RunpSIMS.swift $work_directory
cp bin/RunpSIMS.sh $work_directory
cp conf/swift.properties $work_directory
cp conf/$site.xml $work_directory/sites.xml
cp conf/$site.cf $work_directory/cf
cp $paramfile $work_directory/paramfile
chmod a+rw $work_directory/*

cd $work_directory
source params.psims

# Extract input_tars
if [ -n "$tar_inputs" ]; then
   echo "Setting up data..."
   tar_files=$( echo $tar_inputs | sed s/,/' '/g )
   for file in $tar_files; do
      extension="${file##*.}"
      if [ "$extension" == "tar" ]; then
         echo "Extracting $file"
         tar xf $file 
      else
         echo "Extracting $file"
         tar xfz $file 
      fi
   done
fi

# Record arguments in ABOUT file
cat << EOF > ABOUT
Running with parameter file $( abspath $paramfile )
Running on site $site
Running with gridlist $( abspath $gridlist )
Run directory $rundir
Work directory $work_directory
EOF

# Echo parameters
echo
cat ABOUT
echo -e "\nParameters:"
cat $work_directory/params.psims
echo

# Do the run
for param in $( awk '{print $1}' paramfile )
do
   arguments="$arguments -$param=${!param}"
done

export SWIFT_HEAP_MAX=5120M
export SWIFT_USERHOME=$PWD

echo "swift -sites.file sites.xml -tc.file tc.data -config cf -resume *.rlog RunpSIMS.swift $arguments 2>&1 | tee -a swift.out" > restart.sh
chmod +x restart.sh

gensites -p cf $rundir/../conf/$site.xml > sites.xml
swift -sites.file sites.xml -tc.file tc.data -config cf RunpSIMS.swift $arguments 2>&1 | tee swift.out

echo Generating plot...
$rundir/../bin/activityplot.pl RunpSIMS-2*.log &> /dev/null
echo Done

# Move data back to original run directory
if [ "$rundir" != "$work_directory" ]; then
   echo Moving data from $work_directory to $rundir...
   mv $work_directory/* $rundir/
   rm -r $work_directory
   echo Done
fi
