unit DLGCenWF;

interface

uses
  Windows, Messages, SysUtils, Variants, Classes, Graphics, Controls, Forms,
  Dialogs, ComCtrls, StdCtrls,
  SCClass, ExtCtrls, Buttons, Grids;

type
  TDLGCenW = class(TForm)
    lstBxCenW: TListBox;
    PC: TPageControl;
    OKBtn: TButton;
    Button1: TButton;
    HelpBtn: TButton;
    TabSheet1: TTabSheet;
    TabSheet2: TTabSheet;
    TabSheet3: TTabSheet;
    TabSheet4: TTabSheet;
    TabSheet5: TTabSheet;
    TabSheet6: TTabSheet;
    TabSheet7: TTabSheet;
    TabSheet8: TTabSheet;
    TabSheet9: TTabSheet;
    rgCalculation: TRadioGroup;
    chkIsotopes: TCheckBox;
    edtResetPlantPools: TCheckBox;
    grpLignin: TGroupBox;
    grpCoarseLitter: TGroupBox;
    grpOMLayers: TGroupBox;
    rgLayerOption: TRadioGroup;
    btnLitterInput: TButton;
    grpAllocation_Terms: TGroupBox;
    grpAllocation_Ratios: TGroupBox;
    grpStem_Allom_Paras: TGroupBox;
    grpAllometric_H_vs_dbh: TGroupBox;
    grpNRatios: TGroupBox;
    grpTable: TGroupBox;
    btnInsert: TBitBtn;
    btnDuplicate: TBitBtn;
    btnDelete: TBitBtn;
    btnDeleteAll: TBitBtn;
    btnLoad: TBitBtn;
    btnSave: TBitBtn;
    btnSoilLitter: TButton;
    GroupBox1: TGroupBox;
    BitBtn1: TBitBtn;
    BitBtn2: TBitBtn;
    BitBtn3: TBitBtn;
    BitBtn4: TBitBtn;
    BitBtn5: TBitBtn;
    BitBtn6: TBitBtn;
    grpLeafPhotosyntheticParameters: TGroupBox;
    Stomatal_Conductance_Parameters: TGroupBox;
    Temperature_Damage: TGroupBox;
    Temperature_Response: TGroupBox;
    Age_Decline: TGroupBox;
    rgIncludeAge: TRadioGroup;
    Foliage_clumping: TGroupBox;
    edtFoliageClumping: TCheckBox;
    gpConstantLeafN: TGroupBox;
    edtConstantLeafN: TCheckBox;
    grpIsotopes: TGroupBox;
    rgCalcNewDelta: TRadioGroup;
    grpTypeOfEvap: TGroupBox;
    rgCalc: TRadioGroup;
    chkAcclimation: TCheckBox;
    rgMortalityType: TRadioGroup;
    grpFoliageSenesc: TGroupBox;
    grpAnnualSenesc: TGroupBox;
    grpUseCarbo: TGroupBox;
    grpSystemNutrientDynamics: TGroupBox;
    GroupBox2: TGroupBox;
    RadioGroup1: TRadioGroup;
    Label2: TLabel;
    Label3: TLabel;
    Label4: TLabel;
    Label5: TLabel;
    Label6: TLabel;
    Label7: TLabel;
    Label8: TLabel;
    Label9: TLabel;
    Label10: TLabel;
    Label11: TLabel;
    Label12: TLabel;
    Label13: TLabel;
    Label14: TLabel;
    Label15: TLabel;
    Edit1: TEdit;
    Edit2: TEdit;
    Edit3: TEdit;
    Edit4: TEdit;
    Edit5: TEdit;
    Edit6: TEdit;
    Edit7: TEdit;
    Edit8: TEdit;
    Edit9: TEdit;
    Edit10: TEdit;
    Edit11: TEdit;
    Edit12: TEdit;
    Edit13: TEdit;
    Edit14: TEdit;
    Label16: TLabel;
    Label17: TLabel;
    Label18: TLabel;
    Label19: TLabel;
    Label20: TLabel;
    Label21: TLabel;
    Label22: TLabel;
    Label23: TLabel;
    Label24: TLabel;
    Label25: TLabel;
    Label26: TLabel;
    Label27: TLabel;
    Label28: TLabel;
    Label29: TLabel;
    Label30: TLabel;
    Label31: TLabel;
    Label32: TLabel;
    Label33: TLabel;
    Label34: TLabel;
    Label35: TLabel;
    Label36: TLabel;
    Label37: TLabel;
    Label38: TLabel;
    Label39: TLabel;
    Label40: TLabel;
    Label41: TLabel;
    Label42: TLabel;
    Label45: TLabel;
    Edit15: TEdit;
    Edit16: TEdit;
    Edit17: TEdit;
    Edit18: TEdit;
    Edit19: TEdit;
    Edit20: TEdit;
    Edit21: TEdit;
    Edit22: TEdit;
    Edit23: TEdit;
    Edit24: TEdit;
    Edit25: TEdit;
    Edit26: TEdit;
    Edit27: TEdit;
    Edit28: TEdit;
    Edit29: TEdit;
    Edit30: TEdit;
    Edit31: TEdit;
    Edit32: TEdit;
    Edit33: TEdit;
    Edit34: TEdit;
    Edit35: TEdit;
    Edit36: TEdit;
    Edit37: TEdit;
    Edit38: TEdit;
    Edit39: TEdit;
    Edit40: TEdit;
    Edit41: TEdit;
    Label43: TLabel;
    Label44: TLabel;
    Label47: TLabel;
    Label48: TLabel;
    Label49: TLabel;
    Label50: TLabel;
    Label51: TLabel;
    Label52: TLabel;
    Label53: TLabel;
    Label54: TLabel;
    Label55: TLabel;
    Label56: TLabel;
    Label57: TLabel;
    Label58: TLabel;
    Label59: TLabel;
    Label60: TLabel;
    Label61: TLabel;
    Label62: TLabel;
    Label63: TLabel;
    Label64: TLabel;
    Label65: TLabel;
    Label66: TLabel;
    Label67: TLabel;
    Label68: TLabel;
    Label69: TLabel;
    Label70: TLabel;
    Label46: TLabel;
    Edit42: TEdit;
    Edit43: TEdit;
    Edit44: TEdit;
    Edit45: TEdit;
    Edit46: TEdit;
    Edit47: TEdit;
    Edit48: TEdit;
    Edit49: TEdit;
    Edit50: TEdit;
    Edit51: TEdit;
    Edit52: TEdit;
    Edit53: TEdit;
    Edit54: TEdit;
    Edit55: TEdit;
    Edit56: TEdit;
    Edit57: TEdit;
    Edit58: TEdit;
    Edit59: TEdit;
    Edit60: TEdit;
    Edit61: TEdit;
    Edit62: TEdit;
    Edit63: TEdit;
    Edit64: TEdit;
    Edit65: TEdit;
    Edit66: TEdit;
    Edit67: TEdit;
    Edit68: TEdit;
    Edit69: TEdit;
    Label71: TLabel;
    Label72: TLabel;
    Label73: TLabel;
    Label74: TLabel;
    Label75: TLabel;
    Label76: TLabel;
    Label77: TLabel;
    Label78: TLabel;
    Label79: TLabel;
    Label80: TLabel;
    Label81: TLabel;
    Label82: TLabel;
    Label83: TLabel;
    Label84: TLabel;
    Label85: TLabel;
    Label86: TLabel;
    Label87: TLabel;
    Label88: TLabel;
    Label89: TLabel;
    Label90: TLabel;
    Label91: TLabel;
    Label92: TLabel;
    Label93: TLabel;
    Label94: TLabel;
    Label95: TLabel;
    Label96: TLabel;
    Label97: TLabel;
    Label98: TLabel;
    Label99: TLabel;
    Label100: TLabel;
    Label101: TLabel;
    Label102: TLabel;
    Label103: TLabel;
    Label104: TLabel;
    Label105: TLabel;
    Label106: TLabel;
    Label107: TLabel;
    Label108: TLabel;
    Label109: TLabel;
    Label110: TLabel;
    Edit70: TEdit;
    Edit71: TEdit;
    Edit72: TEdit;
    Edit73: TEdit;
    Edit74: TEdit;
    Edit75: TEdit;
    Edit76: TEdit;
    Edit77: TEdit;
    Edit78: TEdit;
    Edit79: TEdit;
    Edit80: TEdit;
    Edit81: TEdit;
    Edit82: TEdit;
    Edit83: TEdit;
    Edit84: TEdit;
    Edit85: TEdit;
    Edit86: TEdit;
    Edit87: TEdit;
    Edit88: TEdit;
    Edit89: TEdit;
    Edit90: TEdit;
    Edit91: TEdit;
    Edit92: TEdit;
    Edit93: TEdit;
    Edit94: TEdit;
    Edit95: TEdit;
    Edit96: TEdit;
    Edit97: TEdit;
    Label111: TLabel;
    Label112: TLabel;
    Label113: TLabel;
    Label114: TLabel;
    Label115: TLabel;
    Label116: TLabel;
    Label117: TLabel;
    Label118: TLabel;
    Label119: TLabel;
    Label120: TLabel;
    Label121: TLabel;
    Label122: TLabel;
    Label123: TLabel;
    Label124: TLabel;
    Label125: TLabel;
    Label126: TLabel;
    Edit98: TEdit;
    Edit99: TEdit;
    Edit100: TEdit;
    Edit101: TEdit;
    Edit102: TEdit;
    Edit103: TEdit;
    Edit104: TEdit;
    Edit105: TEdit;
    Edit106: TEdit;
    Edit107: TEdit;
    Edit108: TEdit;
    Edit109: TEdit;
    Edit110: TEdit;
    Edit111: TEdit;
    Edit112: TEdit;
    Edit113: TEdit;
    Label127: TLabel;
    Edit114: TEdit;
    sgPhen: TStringGrid;
    Edit115: TEdit;
    sgSO: TStringGrid;
    Label1: TLabel;
    Edit116: TEdit;
    procedure FormCreate(Sender: TObject);
    procedure FormDestroy(Sender: TObject);
  private
    { Private declarations }
    curridx:integer;
  public
    { Public declarations }
  end;

var
  DLGCenW: TDLGCenW;
  myclass:TSClass;

implementation

{$R *.dfm}
uses
  CNCCenwTypes,CNCCenW;

procedure TDLGCenW.FormCreate(Sender: TObject);
var
  i:integer;
  s:tSInstance;
  cw:CenW;
  p:^parameterType;
begin
  // need to get the Pow_Sig class from the database.
  for i := 0 to myClass.Scriptablenames.count-1 do
  Begin
    s:=myclass.scriptablenames[i];
    cw:=CenW(s.scriptable);
    new(p);
    p^:=cw.parameter;
    //ls:=TLinearSetting.Create;
    lstBxCenw.items.AddObject(cw.FullName,(TObject(p)));
  end;
  if lstBxCenW.count>0 then
  Begin
    currIdx:=0;
    lstBxCenW.Itemindex:=0;
    //setting2DLG(curridx);
    //plot(curridx);
  end;
end;

procedure TDLGCenW.FormDestroy(Sender: TObject);
var
  i:integer;
  p:^parameterType;
begin
  for i := 0 to lstBxCenw.Count-1 do
  Begin
    p:=Pointer(lstBxCenW.Items.Objects[i]);
    dispose(p);
  end;
end;

end.
